-- Retrieving all Data from Dataset
SELECT * FROM customer;

-- Q.1 What is the Total Revenue Generated by Male vs Female Customer ?
SELECT gender , SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

-- Q.2 Which Customers useed a discount but still spent more than the avergae purchase amount ?
 SELECT customer_id , purchase_amount
 FROM customer
 WHERE discount_applied= 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

 -- Q.3 Which are the top 5 products with the highest average reviiew rating ?
 SELECT item_purchased , ROUND(AVG(review_rating::numeric),2) AS "Average Product Rating"
 FROM customer
 GROUP BY item_purchased
 ORDER BY AVG(review_rating) DESC
 LIMIT 5;

 -- Q.4 Compare the Average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q.5 Subscriber vs Non - Subscribers Customers by Total Revenue
SELECT subscription_status,
COUNT(customer_id) as total_customers,
	ROUND(AVG(purchase_amount), 2) AS avg_spend,
	ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

-- Q.6 Top 5 Product with Highest Percentage of purchase with discount applied 
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q.7 Segment customer into New , Returning and Loyal Based on their total number of previous purchase and show the count of each segment
with customer_type as (
SELECT customer_id, previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'New'
	 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--Q.8 Top 3 Most purchased product with each category
WITH item_count AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    total_orders,
    item_rank
FROM item_count
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q.9 Are customers who are repeat buyers (more then 5 previous purchases) are also likely to Subscribe ?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q.10 what is the revenue contribution of each age group
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;